### ISSUE TITLE
Favicon / Logo

### ISSUE THREAD

**Issue by angristan** [Flood-UI/flood#165]
To improve the overall UI and add a recognition sign for the users, it would be great if someone could do a simple logo, so we can have a favicon.

**Comment by jfurrow** [comment]
This is on my long list of `TODO`s. Here's some progress on the logo: https://dribbble.com/shots/2855254-Flood-Logo

**Comment by Angristan** [comment]
This logo is really good !

**Comment by jfurrow** [comment]
Thanks @Angristan! A simplified favicon is coming soon...

**Comment by jfurrow** [comment]
Reopening this until I actually resolve the issue...

**Comment by halo779** [comment]
One thing i will point out with the current planned logo there is, It looks much like the deluge icon. May cause confusion depending on the time-gap between implementation and #185 is complete!

Otherwise looks great!

**Comment by DavePS** [comment]
+1, for my instance I use an nginx trick to use my own favicon.

`location ~ /(favicon.ico|apple-touch-icon.png)$ {
  root /var/www/icons;
 }`

**Comment by jfurrow** [comment]
@halo779 Well that's embarrassing, I didn't intentionally steal the Deluge logo concept, but they are far too similar... I'll work on this...

**Comment by noraj1337** [comment]
Here are the two logo side by side:

![](http://i.imgur.com/mmNUPSX.jpg)

**Comment by noraj1337** [comment]
Deluge is raining so a drop is suitable.
For flood instead of a drop you may want to draw one or several little waves. Or maybe some water submerging something.

**Comment by karibuTW** [comment]
How about keeping the waves, but remove the bottom and upper part that makes it a drop?

**Comment by noraj1337** [comment]
@karibuTW Yeah that could be nice

**Comment by NoLooseEnds** [comment]
I made a quick logo with favicons (pull req here: https://github.com/jfurrow/flood/pull/363), I got tired of searching for Flood in among my browser tabs. 

I don't want to step on any toes, but it should work as a (temporary) alternative. :)

![flood_mockup](https://cloud.githubusercontent.com/assets/4103531/26130781/45133034-3a8e-11e7-9041-b6d4367a5fd4.png)
![android-chrome-512x512](https://cloud.githubusercontent.com/assets/4103531/26130795/59c17df6-3a8e-11e7-8a19-d55f286d8a4a.png)

**Comment by noraj1337** [comment]
Nice work.

**Comment by jfurrow** [comment]
This is looking pretty sweet! Thanks for doing this. I did have a different
direction in mind for Flood but this is a great start, so I'm inclined to
merge this.

That being said, I'm traveling in the carribean and have super spotty
internet until next week Wednesday. I'll try to find time to review this.

**Comment by nVitius** [comment]
For what it's worth, I really like the icon @jfurrow shared earlier in this thread. It's got a totally different feel than the Deluge one, so I don't think that's an issue.

**Comment by noraj** [comment]
2 years that flood is using this logo as the official one, so i'll close this issue.
