### ISSUE TITLE
can't start flood on Windows

### ISSUE THREAD

**Issue by lustyffh** [Flood-UI/flood#178]
Hi, I'm complete noob with node.js. I ran npm install with no issues. However nmp run start:production returns error. Refer to the debug file below What's wrong here?

'0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start:production' ]
2 info using npm@2.15.11
3 info using node@v4.6.2
4 verbose run-script [ 'prestart:production',
4 verbose run-script   'start:production',
4 verbose run-script   'poststart:production' ]
5 info prestart:production flood@0.0.0
6 info start:production flood@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info flood@0.0.0 Failed to exec start:production script
9 verbose stack Error: flood@0.0.0 start:production: `npm run prestart; node ./server/bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\Andrey\AppData\Roaming\nvm\v4.6.2\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\Andrey\AppData\Roaming\nvm\v4.6.2\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:854:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid flood@0.0.0
11 verbose cwd c:\flood-master
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:production"
14 error node v4.6.2
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error flood@0.0.0 start:production: `npm run prestart; node ./server/bin/www`
17 error Exit status 1
18 error Failed at the flood@0.0.0 start:production script 'npm run prestart; node ./server/bin/www'.
18 error This is most likely a problem with the flood package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run prestart; node ./server/bin/www
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs flood
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls flood
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by jfurrow** [comment]
Hey @lustyffh, sorry you're having this issue. Unfortunately I don't see anything very useful in the output you provided, but I do appreciate you providing it!

Can you try running `node ./server/bin/www` from the root of the directory where Flood is cloned and let me know what happens?

**Comment by lustyffh** [comment]
Hi jfurrow, thanx for prompt help. I kind of got what you are leading to. Actually `node ./server/bin/www` will do nothing as this is a unix path. However, I see no issues if I run this command as follows `node c:\flood-master\server\bin\www`. It seems to connect to rtorrent just fine. However, my next question would be how to amend path to www for the flood? It seems there's nothing relevant in the config.js under flood folder.

**Comment by jfurrow** [comment]
@lustyffh I just merged a PR (https://github.com/jfurrow/flood/pull/181) that might fix your issues. Would you mind giving it a shot? Just run `git pull` in the Flood directory to update the `master` branch and run `npm run start:production`.

Your next question, "how to amend path to www for the flood," I'm not sure what you mean by this exactly. Could you please elaborate? Do you mean you want to expose flood at a sub-directory, such as `https://<hostname>/foo/bar/flood`?

**Comment by lustyffh** [comment]
Hi jfurrow, I did as you advised but it didn't help. Just in case, I did fresh install of the flood and attach log file here - https://dl.dropboxusercontent.com/u/59464099/log.txt. 

And by amending the path I mean that `./server/...` is not a notation that windows understands normally. I think `./server/bin/www` is passed to flood as an argument. And that argument, IMO, should have different notation like `c:\flood-master\server\bin\www`.

**Comment by noraj1337** [comment]
@lustyffh : The true problem, I think, is running nodejs/npm under windows.
The true question is, I think, why are you using nodejs/npm under windows, this is not designed for that.

**Comment by lustyffh** [comment]
@noraj1337 : because windows is my desktop platform. designed or not, nodejs/npm is available for windows as an installer. If such is the case then it's assumed all node-js apps are supposed to work on windows as well. I'm not a subject matter expert, but I was always thinking nodejs is abstraction layer. if nodejs is working on the system then all nodejs app should work on that system as well.

**Comment by noraj1337** [comment]
@lustyffh So if it is for your desktop it will be easier to use a fat client. No-GUI + Web-UI like rTorrent + ruTorrent or rTorrent + Flood are designed for server that don't have a graphical environment. But you have one so use something like Deluge, qBittorrent, Transmission, Vuze, Frostwire, PicoTorrent.

Maybe I was wrong about nodejs. But one thing is sure, rTorrent is designed for Unix only : 
https://www.reddit.com/r/trackers/comments/v8jj8/rtorrent_on_windows/
https://rtwi.jmk.hu/wiki/rTorrentOnWindows

Wanting to use rTorrent on Windows is a nonsense.

@jfurrow : please close this issue as wontfix

**Comment by jfurrow** [comment]
I'm not going to close this. Flood should absolutely work on Windows especially because the solution is probably be trivial.

@lustyffh sorry this has taken so long. I'll devote more energy to this ASAP.

**Comment by jfurrow** [comment]
@lustyffh Would you mind trying the PR I just put up? Check out the branch `bug/remove-source-operator-in-package.json` (first run `git fetch origin` then run `git checkout bug/remove-source-operator-in-package.json`). This just removes the source operator (`.`) from the scripts...

What version of Windows are you using? I tested setting up Git, Node, and Flood on Windows 7 and Windows 10 and everything worked fine for me (I did not install rtorrent but that obviously wouldn't have any impact on these bash scripts not working). I did have Cygwin installed on Windows 7, but I used the "Command Prompt" app (I'm not sure if that matters).

**Comment by Lukyczk** [comment]
Hi, i was trying to install Flood for the couple last days, and it was a nightmare... Now im stuck at Exit code 8. I tried running the command you wrote, and it gave me this: patebin.com/mwp7beM9

**Comment by jfurrow** [comment]
@Lukyczk I'd be happy to help you in a separate issue as this one is related to problems running Flood on Windows. When you file the separate issue, please include which version of Node you have installed — it looks like the error you're receiving is due to an outdated version (you should be on 6.9 or above).

**Comment by nVitius** [comment]
There's a related issue for this on npm: https://github.com/npm/npm/issues/13789
@lustyffh if you really want to run this on Windows, I would suggest you either use Windows 10's new Bash shell, or run it using Docker.

@jfurrow we might be able to solve this simply by using a Gulp task to run the server too.

**Comment by wopian** [comment]
This isn't an issue if you use `yarn`

**Comment by bbashy** [comment]
Is this still an issue on Win10?

**Comment by noraj** [comment]
Several options in 2019:

- run Flood from Linux (preferred)
- run Flood from docker
- run flood from WSL on Windows 10

So I'll close this issue.
