### ISSUE TITLE
Add fast resume option

### ISSUE THREAD

**Issue by jfurrow** [Flood-UI/flood#252]
Originally requested in #204 

I don't fully understand the requirement, but there's a Perl script in the rTorrent repo which does this, so essentially that should be translated to Javascript. https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#adding-fast-resume-data-to-torrent-files

This is honestly not a high priority for me, so it would be great if somebody could rewrite that Perl script in Javascript. If someone provides that, I'll handle the implementation into the Flood UI & node server.

**Comment by xiayyu** [comment]
Hi jfurrow,
I tried to rewrite the below python script into Javascript, which can add fast_resume data to a torrent file for rtorrent, and tested well for my local environment.

python scripts from pyroscope:
https://github.com/pyroscope/pyrocore/blob/4329ca814cab34e18519c3535ffacb117094847e/src/pyrocore/util/metafile.py#L290

my rewrited javascripts:
https://gist.github.com/xiayyu/1f3402c7c011489386d46fd29d3e0ca3

The `fast_resume_test.js` will make a torrent exactly the same as the torrent genrated by pyroscope's tool script `chtor`, which I have checked their md5sums.

Usually I use `chtor` to add fast_resume data to a torrent file and then deliver it to rtorrent via flood. Rutorrent employs the perl script, but with a defect as:
https://github.com/rakshasa/rtorrent/issues/531

I'm quite new to javascripts, the deffirent standars and the asynchronous functions drive me to crazy.

**Comment by xiayyu** [comment]
@jfurrow I have implemented this in my fork Repositories
https://github.com/jfurrow/flood/compare/master...xiayyu:dev

**Comment by SF4L** [comment]
Is there a way to add a torrent in 'fast resume' mode for cross-seeding purposes?

![untitled](https://user-images.githubusercontent.com/36459489/36176668-5dd8aaf2-10e1-11e8-9109-2d4107cc77ef.png)

**Comment by muertocaloh** [comment]
Hi,
Is there any update on this?

**Comment by jesec** [comment]
Resolved by 3f8172d43c7b5c43b0d949a6e75f47b533ee8eab.
