### ISSUE TITLE
Mediainfo doesn't work on windows

### ISSUE THREAD

**Issue by vBm** [Flood-UI/flood#313]
MediaInfo is present in the path so it can be run from command prompt just fine.

![2017-04-19_18-30-44](https://cloud.githubusercontent.com/assets/80596/25190981/52dc1138-252e-11e7-9042-23fdc15f5ca8.png)

When trying to access MI via flood I get it's error msg `An error occurred while running mediainfo on the server. Check that mediainfo is installed and available in the PATH to Flood.`

Console is showing this:
![2017-04-19_18-25-45](https://cloud.githubusercontent.com/assets/80596/25191036/82d4b840-252e-11e7-9391-0080d9771430.png)

Checking flood's log we see this:

![2017-04-19_18-34-19](https://cloud.githubusercontent.com/assets/80596/25191114/d35a2836-252e-11e7-8919-064bd2c21956.png)

It must be somehow related to #311

**Comment by jfurrow** [comment]
Thanks for the issue, I'll look into this ASAP.

**Comment by Wonderfall** [comment]
Maybe it's not related, but it used to work in my Docker container, and since I updated to 1.0 Mediainfo is not working anymore.

**Comment by sohorx** [comment]
hi, 
I've got the same error on arch and is probably related to this [issue 342 fix proposal](https://github.com/jfurrow/flood/issues/342).

**Comment by noraj** [comment]
@vBm Can you confirm it is still present with the last version?

**Comment by vBm** [comment]
@noraj Unfortunately I don't use flood anymore.
