### ISSUE TITLE
Option to download files directly to destination

### ISSUE THREAD

**Issue by nVitius** [Flood-UI/flood#327]
If I'm downloading a torrent that is a folder, I'd like to have the files inside the folder placed directly in the selected destination.

The current functionality is such that if I make a torrent from this folder: `bar/baz.abc`
And I set the destination to `foo/`
the file will be available in `foo/bar/baz.abc`. I want the file to be placed in `foo/baz.abc`.

ruTorrent has an option on the "add torrent" dialog labeled "Don't add torrent's name to directory". You can see it in [this screenshot](https://raw.githubusercontent.com/wiki/Novik/ruTorrent/images/scr3_big.jpg)

**Comment by jfurrow** [comment]
Thanks for the issue (and the PR)! I agree this option is necessary.

**Comment by runaroundhome** [comment]
This can be closed can't it? As it was added back in 2017 https://github.com/Flood-UI/flood/pull/340
