### ISSUE TITLE
[Request] Create torrent from file

### ISSUE THREAD

**Issue by EternalBlack** [Flood-UI/flood#332]
First of all: thanks for the awesome work!

I would love to create torrents i.e. uploading a file (either via browser/webinterface or via FTP inside the folder) and creating a torrent file/URL or magnet link from it to be available for others.

**Comment by nVitius** [comment]
For the record, it looks like rtorrent doesn't have functionality to create torrents itself. ruTorrent handles this with this code:
https://github.com/Novik/ruTorrent/blob/master/php/Torrent.php
https://github.com/Novik/ruTorrent/tree/master/plugins/create

WebTorrent has a JavaScript package for creating torrents that we might be able to leverage:
https://github.com/webtorrent/create-torrent

**Comment by jfurrow** [comment]
Thanks for the issue @EternalBlack! I agree, this is necessary.

Thanks for doing some research @nVitius, `create-torrent` looks like it should work!

**Comment by jvacek** [comment]
Would just like to make sure that if this is implemented, the source option should be supported. Rudde's mktorrent does this. I'm in no way knowleadgeable with JS or node, but looks like someone already took a stab at making this work from js.

https://github.com/Rudde/mktorrent
https://github.com/bbqsrc/node-mktorrent

**Comment by SavageCore** [comment]
Yes source support is crucial. Should await the merge of https://github.com/webtorrent/create-torrent/pull/49

**Comment by DMCK96** [comment]
Any luck on this, now that source support has been added to webtorrent?

**Comment by T-z3P** [comment]
Hello, any updates on this? I really think is a useful enhancement for Flood.

**Comment by Californian** [comment]
I think this should be closed, since it looks like this has been merged in.
