### ISSUE TITLE
EventSource is not supported by Edge

### ISSUE THREAD

**Issue by wopian** [Flood-UI/flood#437]
[EventSource](http://caniuse.com/#search=eventsource) is still under consideration for Edge with over [5000 votes][1]. In the meantime, Flood is completely unusable for those users, where they'll only ever see the dark blue background

There's a fairly lightweight [polyfill](https://github.com/Yaffle/EventSource) available for Edge if its not implemented any time soon.

[1]:https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serversenteventseventsource/

**Comment by randomnonsense** [comment]
So don't use Edge. Nobody sane uses it anyway. Try chromium. You can download a clean versions without any google sync crap here: https://chromium.woolyss.com/

**Comment by jfurrow** [comment]
Yeah, Flood should polyfill `EventSource`.
