### ISSUE TITLE
Expand eslint rules

### ISSUE THREAD

**Issue by jfurrow** [Flood-UI/flood#555]
Let's have better eslint rules.

I think I'd like to use [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) for the client-side JS and [eslint-config-airbnb-base](https://www.npmjs.com/package/eslint-config-airbnb-base) for server-side.

Any thoughts?

**Comment by dcousens** [comment]
Personally I use https://standardjs.com/ - that will be my +1 :+1:

**Comment by noraj1337** [comment]
I'm for the more standard lint rules and standardjs seems to be good for that. Additionally it seems to be supported by some atom plugins like [linter-js-standard](https://atom.io/packages/linter-js-standard).

**Comment by jesec** [comment]
Flood now uses `airbnb-typescript` with minimal exceptions.
