### ISSUE TITLE
[REQ] Would it be possible to add auto completion or select folder by keyboard letters? When selecting destination folder

### ISSUE THREAD

**Issue by CluelessTechnologist** [Flood-UI/flood#632]
## Summary

So I would like to be able to select a folder with my keyboard.

## Expected Behavior

![recorded_rutorrent](https://user-images.githubusercontent.com/37050524/36990887-4a989e8c-20a6-11e8-9d61-bf7c0dafc6ff.gif)

ruTorrent has this function. When I browse for a directory I can for example select the first folder that starts with a t if I press t on my keyboard.

## Current Behavior

![recorded](https://user-images.githubusercontent.com/37050524/36990989-a18bf2a2-20a6-11e8-84c0-3cfecdc52bd9.gif)

Nothing happens if I do this in flood. I can only select folders with the mouse.

## Possible Solution

Another solution I would be happy with is auto completion. If you begin to type the folder you want to save to in the destination field and press tab for auto completion. 

## Context

This is really nice to have if you have a lot folders in your download directory like I have.
If you really wanna beat ruTorrent you can go overkill with several letters like in Windows Explorer.
Where you can select a folder quickly by typing the begining of the folder name.
For example if you have loads of folders and you are looking for a folder called "Apple" you can press Appl fast and it will select Apple. 

## Your Environment

* Version used:
  + Version (stable release) `flood@1.0.0 `
  + Commit ID (development release) `v1.0.0-285-g2cb40c4`
* Environment name and version (e.g. Chrome 39, node.js 5.4): FireFox 58.0.2 (64-bit)
* Operating System and version: Debian Stretch

**Comment by noraj1337** [comment]
@CluelessTechnologist Please read and  respect the issue template.

**Comment by CluelessTechnologist** [comment]
@noraj1337 Can you reopen this? I have edited the issue to follow the template.

**Comment by jesec** [comment]
@CluelessTechnologist 4.5 includes a change that may resolve this issue. Please try it out, and feel free to close the issue if it has been resolved.

**Comment by CluelessTechnologist** [comment]
> @CluelessTechnologist 4.5 includes a change that may resolve this issue. Please try it out, and feel free to close the issue if it has been resolved.

Yes! Many thanks this is exactly what I've been looking for! 
Feel free to claim this [bounty](https://www.bountysource.com/issues/55785125-req-would-it-be-possible-to-add-auto-completion-or-select-folder-by-keyboard-letters-when-selecting-destination-folder?show_profile_modal=1) @jesec
