### ISSUE TITLE
Move flood to an organization

### ISSUE THREAD

**Issue by noraj** [Flood-UI/flood#672]
## Summary

Flood is an open-source project that begin to have an certain amount of collaborators and members. To get more possibilities and keep it cleaner we should move to an organization.

## Expected Behavior

Flood would be an organization containing multiple repositories such as flood and flood-ui-kit.

## Current Behavior

[Flood](https://github.com/jfurrow/flood) repo and [Flood-ui-kit](https://github.com/jfurrow/flood-ui-kit) repo are personal repository.

## Possible Solution

Move Flood projects to an organization.

## Related issues

#545

## How to

- [ Transferring to an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization)

## Benefits

- [Differences between user and organization accounts](https://help.github.com/articles/differences-between-user-and-organization-accounts/)
  + A free plan with unlimited collaborators on unlimited public repositories
  + Unlimited membership with a variety of roles that grant different levels of access to the organization and its data
  + The ability to give members a range of access permissions to your organization's repositories
  +  Nested teams that reflect your company or group's structure with cascading access permissions and mentions : so we could be able to make a core team, an UI team, a issue management team, etc...
  + etc...
- [Repository permission levels for an organization](https://help.github.com/articles/permission-levels-for-an-organization)
- [Permission levels for an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization)
- regroup flood repositories into the same organization

@jfurrow With organization you can continue to be the owner and keep the power.

## Target organization

https://github.com/Flood-UI

**Comment by noraj** [comment]
@jfurrow The move is very easy, I did it on gitlab, you have just to create an organization account, make @jfurrow the owner of it, transfer the two flood repositories to the organization, add some members, updates some hardcoded URL, and the job is done.

**Comment by jfurrow** [comment]
Seems like a good idea. I'll consider this.

**Comment by sachk** [comment]
Since GitHub is being bought out by Microsoft, it might be a good idea to move this project to GitLab or somewhere similar.

**Comment by sachk** [comment]
I'm personally fine with it, but I know many people aren't.

**Comment by noraj** [comment]
@sachk I personally prefer GitLab (and I sue it for my projects) but GitHub is more popular so it's easier to get a community from it.

But I don't think that GitHub being bought by Microsoft will change anything.

But anyway the discussion of this issue is to move flood from a personal repository to an organization not necesserly to move it to another git forge.

**Comment by KingDuckZ** [comment]
@wopian I'm personally in favour of Gitea. I'm not going to contribute to anything hosted on github anymore, in fact I'm planning to close my account as soon as my move to Gitea is complete.

**Comment by noraj** [comment]
@KingDuckZ This issue is not about moving flood to Gitlab, Gitea or whatever, is is about to move from a personal repository to an organization.

**Comment by KingDuckZ** [comment]
@noraj yes, I was answering to this question: "what does moving to a service hosted on Microsoft Azure accomplish?"

**Comment by noraj** [comment]
Since this issue is open, people only talk about Github bought by Microsoft but this is not the subject of the issue. To keep the issue comment area clean, I locked comments for members only.

**Comment by jfurrow** [comment]
I definitely don't plan to move away from GitHub. Still open to the organization idea.

**Comment by noraj** [comment]
I already did it for some projects, this is a matters of minutes, it's very easy.

**Comment by noraj** [comment]
@jfurrow I plan to move some of my personal projects (repository) to a group (organization).

Maybe those issues TODO lists will help not to forget things:

- https://gitlab.com/noraj/rawsec-inventory-twitter-bot/issues/1
- https://gitlab.com/noraj/rawsec-cybersecurity-list/issues/50
- https://gitlab.com/noraj/Rawsec-website/issues/1

**Comment by noraj** [comment]
@jfurrow You should really create a Flood organization on Github in order to scale better and allow to have a true community. This won't take more than 30min to make the change.

**Comment by noraj** [comment]
@jfurrow I created the organization and invited you. https://github.com/Flood-UI
As soon as you accept the invite I will put you as owner of the organization then you will just have to transfer the repo.

**Comment by noraj** [comment]
As @zawapete said in #673 we need an answer on where this project is going, because now that you are inactive this project is slowly dying.

**Comment by noraj** [comment]
@jfurrow This is not a reason for closing this issue called **Move flood to an organization**.

At least the organization will allow to:

- have repos like *flood/flood*, *flood/flood-ui-kit* or *flood/core,* *flood/ui-kit*
- have a more granular roles/permissions policy https://help.github.com/articles/repository-permission-levels-for-an-organization/
- have teams, like developers, issue managers, contributors, etc. or specific to docker, UI, documentation, etc.
- other features https://help.github.com/articles/differences-between-user-and-organization-accounts/#organizations

**Comment by noraj** [comment]
For the FOSS debate, let's continue the debate here: #712

**Comment by jfurrow** [comment]
@noraj Admittedly this was closed out of haste, sorry. Let's do this — I just accepted the invitation to the organization you created.

**Comment by noraj** [comment]
@jfurrow You are now owner of the organization https://github.com/Flood-UI

**Comment by jfurrow** [comment]
Thanks @noraj, I'll get my bearings before transferring the repo.

**Comment by noraj** [comment]
@jfurrow Right now the project is dying because you are the only one able to merge and major lackings presented into #712 are likely dissuading anyone to contribute.

**Comment by jfurrow** [comment]
This is done
