### ISSUE TITLE
Settings tabs state isnt set after first login

### ISSUE THREAD

**Issue by euri10** [Flood-UI/flood#710]
## Note

- [x] You may try to follow the update procedure described in the README and try again before opening this issue.
- [x] Before asking for something, please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [x] Before opening a bug issue, please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.
- [x] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).
- [x] Keep in mind that Flood is a [FLOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software#FLOSS) (Free, Libre and Open Source Software), so please try to provide a PR when opening a bug issue. Without contributions the project can't live and with your help fix and request will come faster.
- [x] The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

## Summary

Settings tabs state isnt set after first login

## Expected Behavior

be able to go back and forth to all tabs in the settings right after login

## Current Behavior

There is this error message in the console:
```
ConnectivityTab.js:16 Uncaught TypeError: Cannot read property 'dht' of undefined
    at t.value (ConnectivityTab.js:16)
    at t.value (ConnectivityTab.js:97)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at d._renderValidatedComponent (ReactCompositeComponent.js:819)
    at d.performInitialMount (ReactCompositeComponent.js:359)
    at d.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at Object.updateChildren (ReactChildReconciler.js:119)
    at m._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at m._updateChildren (ReactMultiChild.js:308)
```

other tabs don't function properly as well

## Possible Solution

hitting a Ctrl+F5 for a full reload solves the issue, seems like the state isn't well set after initial login.

## Steps to Reproduce (for bugs)

1.login
2.go to settings
3.click on connectivity
4.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
```
➜  flood git:(master) ✗ git --no-pager tag
v1.0.0
```
  + Commit ID (development release) `git --no-pager log -1`
```
➜  flood git:(master) ✗ git --no-pager log -1
commit e21ab29c8ed10a600ca316fb7e8a88006c5ca512 (HEAD -> master, origin/master, origin/HEAD)
Author: John Furrow <hello@johnfurrow.com>
Date:   Mon Sep 3 17:59:29 2018 -0700

```
* Environment name and version (e.g. Chrome 39, node.js 5.4):

```
/usr/src/app # node -v
v10.1.0
```

```
Chromium
Version 68.0.3440.75 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)
```
* Operating System and version:
`➜  flood git:(master) ✗ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
`

**Comment by jfurrow** [comment]
I think this will be fixed by https://github.com/jfurrow/flood/pull/721, anyone want to verify? You'll need to run `npm run build` to rebuild the app.

**Comment by euri10** [comment]
I tried on branch bug/fix-settings-fetch-failure, removed my container, then did a fresh build, I still face the same issue: click on settings right after registration leads to those errors in the console, 1st one is by clicking on the Connectivity and 2nd one on the Resources

![Imgur](https://i.imgur.com/AMjpIc6.png)

**Comment by bbashy** [comment]
It does something different now.

Some tabs work after logging in (but only for first click). Connectivity one doesn't show at all.

**Comment by jfurrow** [comment]
I can't repro this, maybe it's fixed? Can any of y'all verify?

**Comment by bbashy** [comment]
Looks like it's fixed for me. All settings tabs change contents as they should.
