### ISSUE TITLE
Correct Remote Torrent Adder plugin settings

### ISSUE THREAD

**Issue by DominicMe** [Flood-UI/flood#782]
Type: Question

Has anyone gotten Remote Torrent Adder plugin for chrome to work with flood?

No matter what options I use I can't get it to add torrents. What are correct settings?

Flood is running on port 3200. Should relative path have some value? rutorrent works fine. In my case it was running via proxy so I used port 80 and /rutorrent for relative path. Host is server IP and user/pass same as interface login,

**Comment by Jqnxyz** [comment]
I managed to get it to work like so:
In Remote Torrent Adder's options, click on 'Add Server', select "flood WebUI".
Host: [domain name]
Port: [port, for me I set it up to be 9091]
SSL: _true/checked_
Username/Password: [Flood login credentials for web UI]
Directory: _empty_
Add torrents paused?: _false/unchecked_

I have a subdomain that points to my network's external IP. My router is set up to port forward :9091 to the server that runs Flood.

I have Flood running with an SSL cert generated from certbot, therefore I had to use the external domain name as the host instead of a local IP to prevent certificate errors.

How do you have your Flood config set up?

**Comment by DominicMe** [comment]
I access it locally via IP address which gets redirected to /overview like so: http://192.168.0.100:3200/overview

Seems like it should work but doesn't for me. doesn't matter if relative path is left blank or not.

Config is almost stock. No sure if floodServerProxy could be related.

```
                                                                                                                        /usr/share/webapps/flood/config.js

// This is the configuration file for Flood, a React-based frontend for the
// rtorrent BitTorrent client.
// Copy this file to ./config.js and make changes below.
// config.js must exist before running `npm run build`.

const CONFIG = {
  // This URI will prefix all of Flood's HTTP requests. You _must_ have a web
  // server, like nginx, configured to forward these requests to the Flood
  // web server.
  // For example, if you intend to serve from http://example.com/flood, set this to
  // '/flood' and configure your web server to pass _all_ requests from `/flood` to
  // the root of Flood's web server.
  // Recompiling assets with `npm run build` is needed after each `baseURI` change.
  // See https://github.com/jfurrow/flood/wiki/Using-Flood-behind-a-reverse-proxy
  baseURI: '/',
  // Flood uses a local nedb database to keep track of users, torrents,
  // and activity. The database is regularly purged to remove outdated data.
  // This value dictates how old data is, in milliseconds, before being purged.
  dbCleanInterval: 1000 * 60 * 60,
  // Where to store the local nedb database.
  dbPath: './server/db/',
  // The host that Flood should listen for web connections on.
  // If you want to connect to Flood from hosts other that the one it is running
  // on, you should change this value.
  // To listen on all interfaces, change to `floodServerHost: '0.0.0.0'`..
  floodServerHost: '0.0.0.0',
  // The port that Flood should listen for web connections on.
  floodServerPort: 3200,
  // Used for development. See the "Local Development" section of README.md
  // for detail.
  floodServerProxy: 'http://127.0.0.1:3000',
  // Flood keeps a history of torrent download and upload speeds.
  // This value dictates the number of individual records per period to keep.
  maxHistoryStates: 100,
  // How often (in milliseconds) Flood will request the torrent list from.
  torrentClientPollInterval: 1000 * 2,
  // A unique secret for signing messages with JWT (see https://jwt.io). Change
  // this to something unique and hard to guess.
  secret: 'nuclearflood',
  // Configuration for SSL, if using SSL with the Flood service directly.
  ssl: false,
  sslKey: '/absolute/path/to/key/',
  sslCert: '/absolute/path/to/certificate/'
};
// Do not remove the below line.
module.exports = CONFIG;

```

**Comment by Jqnxyz** [comment]
Taking a look at the [Flood WebUI integration in Remote-Torrent-Adder](https://github.com/bogenpirat/remote-torrent-adder/blob/master/webuiapis/floodWebUI.js), it should pop up details of errors/failures when attempting to add a torrent. (see `RTA.displayResponse`)

Make sure the checkbox **Popups** is set to **True/Checked**, then reply to this thread with any errors.

If you don't see the notification pop up, check your Action Centre if you are on Windows 10 (Ctrl+A).

**Comment by DominicMe** [comment]
Yes, it does show an error. With above settings it shows "Server didn't accept data: 200:" it gets cut off later, now sure if there is a way to copy all the output.

**Comment by Jqnxyz** [comment]
Can you confirm that your server details are similar to [this screenshot](https://i.imgur.com/55rv3Cx.jpg)?

**Comment by DominicMe** [comment]
> Can you confirm that your server details are similar to [this screenshot](https://i.imgur.com/55rv3Cx.jpg)?

My [Setting screenshot](https://i.imgur.com/W1m0Is8.jpg) looks almost identical.

**Comment by Jqnxyz** [comment]
Looks like your settings are meant for _ruTorrent WebUI_ not _flood WebUI_. Could you delete that server config and add a new one with the Server type **flood WebUI**?

See [this screenshot](https://i.imgur.com/La5skTx.jpg) for clarity.

**Comment by DominicMe** [comment]
Ah, damn it. I didn't realise that mattered. Works like a charm now! Thank you!
