### ISSUE TITLE
Chroot users in their home directory instead of letting them have a full view on the server

### ISSUE THREAD

**Issue by Whisper40** [Flood-UI/flood#783]
Type: Feature Request

## Summary
When creating an user in flood, we should be able to choose what type of chroot we want to use. (ie : User "JAMES" is chrooted in /home/james)

## Why ?
It's not possible to let an user have a full view on the server, it's a huge security risk ! 
By default, any user added should only be chrooted in their home directory..
That's not acceptable to let a full view on the server

Picture :  http://prntscr.com/nhoyyh

**Comment by jfurrow** [comment]
Flood's user management is really not meant to restrict this kind of thing.

**Comment by Whisper40** [comment]
This kind of thing has to be managed by Flood, if it's not the job of flood , i don't know who has to do this job. That's a feature of flood that needs to be restricted.

**Comment by jfurrow** [comment]
You could easily configure this on your server (for example using Docker containers), this is not within Flood's scope.

**Comment by Whisper40** [comment]
So if you say that, how can you explain that in rutorrent we do not have this problem, and the user is restricted to his home..

**Comment by zawapete** [comment]
> Flood's user management is really not meant to restrict this kind of thing.

even if my whole code for user management was rewritten and I don't officially appear as the author I humbly consider me as so, and that's exactly the kind of thing that I see as a basic feature (not even in user management, but as abc of security)

anyway, it doesn't matter anymore

**Comment by jfurrow** [comment]
Definitely not. rtorrent has full access to the filesystem. If you want to restrict users' access, it needs to be done for both rtorrent and Flood.
