### ISSUE TITLE
Dockerfile does not build, missing ABOUT.md

### ISSUE THREAD

**Issue by dutchgecko** [Flood-UI/flood#784]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + commit 61b63e9b549b4ae92796b5595f583e4cff388a13
* Environment name and version:
  + Node.js version v10.1.0
    - Docker image node 10.1-alpine
  + npm version 5.6.0
  + Web browser N/A
* Operating System and version:
  + Debian 9
  + Docker version 18.09.5, build e8ff056dbc 

## Summary
Docker image fails to build in Step 12, due to required file `ABOUT.md` not being a part of the COPY steps and not being present for the build:

```
Step 12/21 : RUN npm run build &&     npm prune --production
 ---> Running in cdd2bdc9e83f

> flood@1.0.0 build /usr/src/app
> node client/scripts/build.js

(node:17) ExperimentalWarning: The fs.promises API is experimental
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../../../../../../ABOUT.md' in '/usr/src/app/client/src/javascript/components/modals/settings-modal'
```

The include is in file `client/src/javascript/components/modals/settings-modal/AboutTab.js`

## Possible Solution

Include ABOUT.md in build.

## Steps to Reproduce

1. `docker build .`

**Comment by N3oTraX** [comment]
Same for me since today.
