### ISSUE TITLE
Flood does not recover if communication to rtorrent is cut then restored

### ISSUE THREAD

**Issue by Cubox-** [Flood-UI/flood#789]
Type: Bug Report

- [X] Try to follow the update procedure described in the README and try again before opening this issue.
- [X] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
 Version used:
  + Version (stable release) `git --no-pager tag` : v1.0.0
  + Commit ID (development release) `git --no-pager log -1` : 61b63e9b549b4ae92796b5595f583e4cff388a13
* Environment name and version:
  + Node.js version `node --version` : v12.0.0
  + npm version `npm --version` : 6.9.0
  + Web browser `name and version` : Google Chrome, stable channel.
* Operating System and version:
FreeBSD 12-STABLE

## Summary
If rtorrent crashes, or is stopped, flood will prompt the user to give either a hostname and port, or socket path to rtorrent.
However, if rtorrent is started back, flood will still prompt the user for a new socket path (or hostname+port combo).
## Expected Behavior
flood should try to reconnect to rtorrent. Either without user input, or after being asked to by the user, without requiring them to enter the socket path again
## Current Behavior
User has to enter the rtorrent communication method again

## Possible Solution
Assuming that users of flood does not have changing configuration, flood should try again with the previously set path/host+port. A prompt could be shown to let the user know flood cannot connect to rtorrent, and give the option to change the communication path, but restoring functionality when rtorrent comes back up.

## Steps to Reproduce

1. set up flood
2. kill rtorrent
3. see the prompt to enter communication path to rtorrent instead of flood interface
4. try to refresh this page, relaunch flood.

**Comment by noraj** [comment]
Please respect issue templates, in your case bug report or feature request.

**Comment by Cubox-** [comment]
> Please respect issue templates, in your case bug report or feature request.

Apologies for this. Issue has been fully updated, respecting the template.
