### ISSUE TITLE
Prompt to specify new communication path will fail if user is not an admin

### ISSUE THREAD

**Issue by Cubox-** [Flood-UI/flood#790]
Type: Bug Report

- [X] Try to follow the update procedure described in the README and try again before opening this issue.
- [X] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [X] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
 Version used:
  + Version (stable release) `git --no-pager tag` : v1.0.0
  + Commit ID (development release) `git --no-pager log -1` : 61b63e9b549b4ae92796b5595f583e4cff388a13
* Environment name and version:
  + Node.js version `node --version` : v12.0.0
  + npm version `npm --version` : 6.9.0
  + Web browser `name and version` : Google Chrome, stable channel.
* Operating System and version:
FreeBSD 12-STABLE

## Summary
If rtorrent crashes, or is stopped, flood will ask the user to provide a host+port combinaison, or socket path, to communicate with an instance of rtorrent.
However, if the user is not an admin, the submit button will do nothing, and in the background the request will be denied, the user not being an admin. (Visible using the Network tab of developer options)

Since flood will not recover without specifying a way to communicate with rtorrent, the user is permanently locked out of their account. This can only be fixed if an admin deletes the account and creates it back.

## Possible Solution
This bug will be solved if #789 is addressed.

## Steps to Reproduce

1. set up flood
2. create non-admin user account
3. kill rtorrent instance linked to previously created user account
4. when prompted to enter the communication path, click "Test" then "Submit" and nothing will happen

**Comment by noraj** [comment]
Please respect issue templates, in your case bug report or feature request.

**Comment by Cubox-** [comment]
> Please respect issue templates, in your case bug report or feature request.

Apologies for this. Issue has been fully updated, respecting the template.
