### ISSUE TITLE
Torrents do not save to feed download rule directory

### ISSUE THREAD

**Issue by mirolm** [Flood-UI/flood#793]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
* Version used:
  + Version v1.0.0
  + Commit ID 777760815be74c8e6fc3a36845cb55699904c446
* Environment name and version:
  + Node.js version v11.15.0
  + npm version 6.9.0
  + Web browser Chromium 74.0.3729.131 (Official Build) Arch Linux (64-bit)
* Operating System and version: Arch Linux

## Summary

When i place a feed download rule there is regex, tag and download directory. In one of last commits torrents started to download in default download directory instead of directory that is in the feed download rule.

![default_directory](https://user-images.githubusercontent.com/9135358/57244459-13453a80-7041-11e9-8d4e-83867714e035.png)

![feed_download_rule](https://user-images.githubusercontent.com/9135358/57244484-21935680-7041-11e9-9df9-b7bc29d4ca5a.png)

![torrent_downloaded](https://user-images.githubusercontent.com/9135358/57244494-26580a80-7041-11e9-9682-5bc05824216a.png)

## Expected Behavior

Torrents to download in directory noted in feed download rule.

## Current Behavior

Torrents download to default download directory.

## Possible Solution

Do not know.

## Steps to Reproduce
1. Put default download directory in Flood options.
2. Create feed definition.
3. Create feed download rule and put different directory in the feed rule.
4. When Flood matches the feed rule check where torrent is downloaded.

## Context

Do not know.

**Comment by noraj** [comment]
Did you pick the path in the *Torrent Destination" field by clicking here:
![image](https://user-images.githubusercontent.com/16578570/57245800-0540eb00-703c-11e9-9883-60a72547a320.png)
? Or did you wrote the path manually ?

**Comment by mirolm** [comment]
The full path is "/media/lv2/download/[HorribleSubs] Dororo [720p]".

I tried to reinstall again to get a clean installation, but this ran me to another bug - after that i cannot add new feed due to error.

When i reinstalled to commit 3f76d267fa9dcc1b50872e7c429febd280f15b88 all works fine. It seems something breaks in feeds after this commit.

**Comment by mirolm** [comment]
I tried to reinstall again to get a clean installation, but this ran me to another bug - i cannot add new feed due to error (Issue #792). Clicking the save feed button does nothing. Errors i get you can see below:

``
ReactErrorUtils.js:49 Uncaught TypeError: e.validatedFields[r].isValid is not a function
    at FeedsTab.js:474
    at Array.reduce (<anonymous>)
    at t.value (FeedsTab.js:471)
    at Object.onSubmit (FeedsTab.js:401)
    at o.handleFormSubmit (main.js:1539)
    at Object.o (ReactErrorUtils.js:24)
    at s (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at f (EventPluginHub.js:41)
    at p (EventPluginHub.js:52)
FeedsTab.js:474 Uncaught TypeError: e.validatedFields[r].isValid is not a function
    at FeedsTab.js:474
    at Array.reduce (<anonymous>)
    at t.value (FeedsTab.js:471)
    at Object.onSubmit (FeedsTab.js:401)
    at o.handleFormSubmit (main.js:1539)
    at Object.o (ReactErrorUtils.js:24)
    at s (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at f (EventPluginHub.js:41)
    at p `(EventPluginHub.js:52)
``

When i reinstalled to commit 3f76d267fa9dcc1b50872e7c429febd280f15b88 all works fine - adding feeds and torrents downloading from rules go to the correct folder. 

![correct_folder](https://user-images.githubusercontent.com/9135358/57249620-1abf1080-704e-11e9-90cf-7bee6654c060.png)

It seems something breaks in feeds after this commit.

**Comment by ngseer** [comment]
I can confirm this bug is presented as I'm using Flood from the latest master commit.

**Comment by jfurrow** [comment]
The validation errors should be fixed in https://github.com/Flood-UI/flood/pull/800, I'll look into the incorrect destinations

**Comment by mirolm** [comment]
Great i will wait for both fixes and then test again with clean install.

**Comment by etbusch** [comment]
This is also confirmed on flood 46fdf3cf908cf1fbb4e13eed4052ba0d58c69a1d for me.
