### ISSUE TITLE
Dockerfile fails to build on npm run build

### ISSUE THREAD

**Issue by mtaanquist** [Flood-UI/flood#794]
Type: Bug Report

## Your Environment

* Version used: Latest stable
* Environment name and version: node:10.1-alpine, Docker version 18.09.5, build e8ff056
* Operating System and version: Ubuntu Server 18.04

## Summary
Attempting to build Dockerfile from repository fails.

## Expected Behavior
Build succeeds.

## Current Behavior
Build fails on step 13/22: `Step 13/22 : RUN npm run build &&     npm prune --production`

Following is the output that starts at step 13.
``` ---> Running in 2764b9a428df

> flood@1.0.0 build /usr/src/app
> node client/scripts/build.js

(node:17) ExperimentalWarning: The fs.promises API is experimental
Creating an optimized production build...
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
Failed to compile.

./client/src/javascript/app.js
SyntaxError: /usr/src/app/client/src/javascript/app.js: Unexpected token (18:2)

  16 |
  17 | const appRoutes = (
> 18 |   <Router history={browserHistory}>
     |   ^
  19 |     <Route path="/" component={AppWrapper}>
  20 |       <IndexRoute component={Login} />
  21 |       <Route path="login" component={Login} />
 @ multi ./client/config/polyfills.js ./client/src/javascript/app.js main[1]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Steps to Reproduce
Requires Docker, but the following command generates the same error: `docker build https://github.com/Flood-UI/flood.git --no-cache`

**Comment by ritewhose** [comment]
In the first line of the Dockerfile, if you change `node:10.1-alpine` to `node:12.2-alpine`, that should do it. I'll submit a pull request later tonight.

**Comment by ritewhose** [comment]
I must have gotten disoriented yesterday because changing the node version was definitely not what fixed my builds. The docker builds actually broke because several files were recently added in commit #785 / dbedc6c7a58b734eeb533a1155daf6b8eabc2286 but were not included in the Dockerfile. I've pushed my changes to my docker branch but I still get some build warnings:
```
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.5 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@4.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@4.0.0-beta.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
```
This amounts to three peers: `webpack@^4.0.0` (in package.json), `eslint@>= 4.12.1` (also in package.json) and `ajv@^6.9.1` (not in package.json). I also checked out the commit right before #785, 92e8989c0cce9dce27a2bab50dd32f0893e1713d, and built it. This version only generates one error message of this type:
```
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```
 I have to confess, I don't know enough about node to tell how serious this is. It seems like most of those warnings are about meta-tools, and the web interface still works as far as I can tell playing around with it a bit.

**Comment by mtaanquist** [comment]
Even updating the version of node in the Dockerfile didn't seem to correct anything for me. I started digging into the following error:

`Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .`

And did manage to fix that modifying `"eslintConfig"` in `package.json`:

```js
  "eslintConfig": {
    "extends": "react-app",
    "settings": {
        "react": {
            "pragma": "React",
            "version": "detect"
        }
    }
  },
```

However, that wasn't the issue, evidently, as it's still failing on a SyntaxError in `/usr/src/app/client/src/javascript/app.js`:

```
./client/src/javascript/app.js
SyntaxError: /usr/src/app/client/src/javascript/app.js: Unexpected token (18:2)

  16 |
  17 | const appRoutes = (
> 18 |   <Router history={browserHistory}>
     |   ^
  19 |     <Route path="/" component={AppWrapper}>
  20 |       <IndexRoute component={Login} />
  21 |       <Route path="login" component={Login} />
 @ multi ./client/config/polyfills.js ./client/src/javascript/app.js main[1]
```

I'm not savvy enough with React to figure out why `Router` is an unexpected token.

**Comment by slicepaperwords** [comment]
I stand in basically the same place as @ritewhose, I updated the node version, added .babelrc, .eslintrc.js, and .prettierrc along with the ABOUT.md to my dockerfile and the image creation completes now and I am able to run it, everything seems fine from UI point of view but am getting a few more warnings, but I also don't know a whole lot about node. this is what I see during RUN npm run build && npm prune --production.
Step 12/20 : RUN npm run build &&     npm prune --production
 ---> Running in a5ce55aa0cc0

> flood@1.0.0 build /usr/src/app
> node client/scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  437.73 KB  assets/static/js/main.5a103711.js
  16.38 KB   assets/static/css/main.39304500.css
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.5 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@4.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@4.0.0-beta.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by mtaanquist** [comment]
I tried to do the same, copying over the three files @slicepaperwords mentioned, but now get linting errors on `DiskIcon.js`:

```
Creating an optimized production build...
Failed to compile.

./client/src/javascript/components/icons/DiskIcon.js
  Line 13:  Mixed spaces and tabs  no-mixed-spaces-and-tabs

Search for the keywords to learn more about each error.
 @ ./client/src/javascript/components/torrent-list/Torrent.js 1:2063-2103 1:3789-3797
 @ ./client/src/javascript/components/torrent-list/TorrentList.js
 @ ./client/src/javascript/components/views/TorrentClientOverview.js
 @ ./client/src/javascript/app.js
 @ multi ./client/config/polyfills.js ./client/src/javascript/app.js

./client/src/javascript/components/torrent-list/Torrent.js
  Line 20:  Component definition is missing display name  react/display-name

Search for the keywords to learn more about each error.
 @ ./client/src/javascript/components/torrent-list/TorrentList.js 1:3350-3381 1:17807-17814
 @ ./client/src/javascript/components/views/TorrentClientOverview.js
 @ ./client/src/javascript/app.js
 @ multi ./client/config/polyfills.js ./client/src/javascript/app.js

./client/src/javascript/components/torrent-list/TorrentDetail.js
  Line 73:  Component definition is missing display name  react/display-name
  Line 83:   Component definition is missing display name  react/display-name
  Line 92:  Component definition is missing display name  react/display-name
  Line 97:   Component definition is missing display name  react/display-name

Search for the keywords to learn more about each error.
 @ ./client/src/javascript/components/torrent-list/Torrent.js 1:2517-2560 3:1711-1724 4:524-537 4:797-810 4:930-943
 @ ./client/src/javascript/components/torrent-list/TorrentList.js
 @ ./client/src/javascript/components/views/TorrentClientOverview.js
 @ ./client/src/javascript/app.js
 @ multi ./client/config/polyfills.js ./client/src/javascript/app.js
```

Why is it linting when attempting to build for production? Would it not make more sense that that only happens when building for development?

**Comment by jfurrow** [comment]
I think this is fixed by https://github.com/Flood-UI/flood/pull/796 — can anyone verify?

**Comment by mtaanquist** [comment]
Hi @jfurrow, it completes compilation now. 

There's still a series of warnings from NPM, but I'm not sure how severe they are:
```
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.5 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@4.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@4.0.0-beta.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.7 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Thanks for the update.

**Comment by noraj** [comment]
@slicepaperwords Please format you code blocks with markdown: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

**Comment by jfurrow** [comment]
This should be fixed — @mtaanquist the NPM install warnings should be addressed, but it's low priority a separate issue.
