### ISSUE TITLE
Cannot add more than one torrent at once

### ISSUE THREAD

**Issue by ngseer** [Flood-UI/flood#801]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
* Version used:
  + Commit ID: 46fdf3c
* Environment name and version:
  + Node.js version: `v10.15.2`
  + npm version: `5.8.0`
  + Web browser `Google Chrome 74.0.3729.131 (Official Build) (64-bit)`
* Operating System and version:
  + Ubuntu 19.04 w/ Linux 5.0.0 kernel

## Summary
When I'm trying to click a `+` button next to the `Torrents` input field at the `Add Torrents/By URL` dialogue, UI stays unchanged and an error message appears in a browser console even if the first input field is not empty.

## Expected Behavior
Another input field for a next torrent link appears as it was at the previous releases.

## Current Behavior
UI stays unchanged. An error trace is being printed to the console:
```js
TextboxRepeater.js:44 Uncaught TypeError: n.handleTextboxAddthis is not a function
    at onClick (TextboxRepeater.js:44)
    at Object.o (ReactErrorUtils.js:24)
    at s (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at f (EventPluginHub.js:41)
    at p (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at e.exports (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:250)
    at ReactEventEmitterMixin.js:15
```

**Comment by jfurrow** [comment]
Fixed by https://github.com/Flood-UI/flood/commit/6e030dd4e24ae050a9a3dedc1b2b191841b91b3b
