### ISSUE TITLE
Can't run build after updating

### ISSUE THREAD

**Issue by peioe** [Flood-UI/flood#805]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
v1.0.0

  + Commit ID (development release) `git --no-pager log -1`
commit 912f61abfb66997b89bcf405023772d430ff349d
Author: John Furrow <me@johnfurrow.com>
Date:   Sat May 25 22:42:53 2019 -0700
* Environment name and version:
  + Node.js version `node --version` v11.15.0
  + npm version `npm --version` 6.9.0
  + Web browser `name and version`
* Operating System and version: debian stretch

## Expected Behavior

npm run build should complete

## Current Behavior

npm run build doesn't complete:
```
$ npm run build
flood@1.0.0 build /home/rtorrent/flood
node client/scripts/build.js

Creating an optimized production build...
Failed to compile.
./client/src/sass/style.scss
ValidationError: CSS Loader Invalid Options
 
options should NOT have additional properties
@ ./client/src/sass/style.scss

./client/src/sass/style.scss (./node_modules/css-loader/dist/cjs.js??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/sass-loader/lib/loader.js!./client/src/sass/style.scss)
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
 @ ./client/src/sass/style.scss 2:14-201

npm ERR! code ELIFECYCLE

npm ERR! errno 1
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rtorrent/.npm/_logs/2019-05-27T22_16_41_324Z-debug.log
```

## Steps to Reproduce

1. I just updated following the procedure in the README as usual
2. git pull 
3. npm run build
4.

## Context

Updating flood and running it again.

Sorry if I'm doing something wrong and thanks for any help.

**Comment by peioe** [comment]
Tried a completely fresh install by re-cloning, same error.

**Comment by peioe** [comment]
Someone suggested I remove "minimize: true" from ./flood/client/config/webpack.config.prod.js because he saw that on: https://github.com/webpack-contrib/css-loader/issues/863

I have no idea what that line does, but if I remove it the build runs and I can start flood.

**Comment by jfurrow** [comment]
Looks like you're getting a newer version of `css-loader` for some reason... Flood's using an older version currently, and the `minimize` option is no longer in use.

Regardless, a different plugin is responsible for minifying the bundle, so the dependency should be updated and that option should be removed. I'll address shortly.

**Comment by jfurrow** [comment]
Fixed by https://github.com/Flood-UI/flood/commit/eefeb4e3c1cf32037fafa7b107fb8cbda3dce4d3, update local branch with `git pull` and run `npm run build` again.

**Comment by noraj** [comment]
@jfurrow I saw other project automatically keeping their dependencies up to date with https://dependabot.com/ (there is also https://greenkeeper.io). It may be a big help to configure one that automatically care of that.
