### ISSUE TITLE
Added files to download after completing others files, are not downloaded

### ISSUE THREAD

**Issue by Tchekda** [Flood-UI/flood#809]
Type: Bug Report

- [X] Try to follow the update procedure described in the README and try again before opening this issue.
- [X] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [X] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `v1.0.0`
  + Commit ID (development release) `704205114be5e09a3b4424e15484e333aa85b25e`
* Environment name and version:
  + Node.js version `v11.15.0`
  + npm version `v6.7.0`
  + Web browser `Google Chrome  74.0.3729.169`
* Operating System and version:
Client : Windows 10 (1809)
Server : Debian GNU/Linux 8.11 (jessie)
## Summary

If the torrent is downloaded in many parts, when the first part is shown as completed and the second part is changed from `Don't Download` to another priority and the torrent is restrarted, nothing happens and the second part is not downloaded
## Expected Behavior

The Second must be download as soon it's enabled in the `Files` section or after a restart
## Current Behavior

Nothing happens either after stopping and restarting the torrent or enabling and disabling files
## Possible Solution

Maybe add a EventHandler to listen to this event or try something with rtorrent because it could come from their side...
## Steps to Reproduce

1. Add torrent and disable `Start Torrent`
2. Go to `Torrent Details` then `Files` and put all files you don't want now to `Don't Download`
3. Start the torrent and wait until the selected files are downloaded
4. Go back to `Files` and change some file to `Normal` priority ( and restart the torrent)

## Context

I'm trying to download folder per folder because the storage of my server is very small so i process all the data folder per folder, and i delete each folder after usage

**Comment by noraj** [comment]
> because the storage of my server is very small

Nothing to do with the issue but it seems you bought a VPS for hosting a seedbox, you should rather buy a dedicated server. Take a look at https://www.kimsufi.com/.

**Comment by Tchekda** [comment]
There is no problem with the storage, even if the host is a VPS, there is enough storage on the host when I want to download the new folder

> buy a dedicated server
It's more expensive than a VPS.

**Comment by noraj** [comment]
> I'm trying to download folder per folder because the storage of my server is very small

and

> There is no problem with the storage

are quite the opposite. VPS often have 10-50 GB SSD where dedicated servers often have 500GB+ HDD. 

>  It's more expensive than a VPS.

In general I would say yes, but kimsufi is an exception. With kimsufi VPS and 1st price dedicated servers are nearly at the same price but dedicated servers have much more space.

![image](https://user-images.githubusercontent.com/16578570/63231115-26a69b00-c217-11e9-87a7-ec5ac1064933.png)

![image](https://user-images.githubusercontent.com/16578570/63231122-42aa3c80-c217-11e9-876d-91703f07853a.png)

Has your root problem seems to be about very small storage space on your VPS, I just gave you an advice. Dedeicated server are more suited for seedboxes and VPS for web hosting but you are free to do what you want.

Please don't answer to my comment, let's keep this issue for the big.

**Comment by Tchekda** [comment]
This issue is not about that, here is an example : 

- Add a torrent and unselect "Start automatically"
- Go to Torrent Details, set everything as "Don't download"
- Select first folder of 10Go and set as "Normal Download"
- Start the download 
- Wait until finished
- Use files as needed
- Delete files from Command Line
- Check disk usage with `df -h`, gives > 17Go
- Go back to Torrent Details
- Set first folder to "Don't download"
- Set second folder of 9.5Go as "Normal download"
- Start the Torrent again
- Nothing happens!
- Posting the issue on GitHub
- Getting an answer: Problem with the host machine...

**Comment by MacTwister** [comment]
@Tchekda Before starting the torrent again, have you tried to run "re-hash check" on the torrent. It's a feature in rTorrent to make rtorrent check all files to make sure which chucks is has or does not have on the filesystem, useful especially since your manually deleting files outside rtorrent after getting the first  batch downloaded. After the re-has, rtorrent will say you have 0% and then you can start the torrent agian.

I do not know how to do this through Flood however, I'v only ever doe it when using rtorrent directly.

**Comment by Tchekda** [comment]
I will try this solution, thank you @MacTwister

**Comment by noraj** [comment]
If this answer you question I'll close it for now.
