### ISSUE TITLE
Why does Flood need so much memory

### ISSUE THREAD

**Issue by hansbogert** [Flood-UI/flood#812]
Type: Question

Flood is being killed by my Out of memory Manager, when that happens, Flood's node process is using 1GB of RSS. Why does it need that much mem? That's like 50% of my micro server.

**Comment by jfurrow** [comment]
@hansbogert Please use the issue template

**Comment by hansbogert** [comment]
Actually I was using the template, namely the Question template, which is that terse. Should I make a issue based on the bug template?

**Comment by jfurrow** [comment]
Oh shit sorry @hansbogert I guess I don't know what the templates look like.

**Comment by damolp** [comment]
Profiling looks like it is geoip-lite (it even calls it out on the [package info](https://www.npmjs.com/package/geoip-lite#caveats)). I commented out geoip-lite from `server/util/clientResponseUtil.js` and I'm saving a ton of memory.

I've noticed a bit of leaking memory as well. I'll try using [this](https://www.npmjs.com/package/thorin-geoip-ultralight) to see if I can decrease the memory footprint

**Comment by hansbogert** [comment]
I'm hitting this every 2 days where the OOM comes by and kills flood. @damolp  is there a way to profile my running process to see if geoip-lite is also the culprit in my case?

**Comment by damolp** [comment]
Use the chrome dev tools (go to `chrome://inspect` from your computer) and forward port 9229 from your server, eg: `ssh server -L 9229:localhost:9229`.

Start flood with `node --inspect server/bin/start.js` and click `Memory` in the chrome dev tools and select `Allocation instrumentation on timeline`. After you stop recording (give it like 30 seconds) you should see the memory allocation. If it looks like my screenshot below you'll know it's GeoIP doing it.

<img width="1230" alt="Screen Shot 2019-07-23 at 7 50 14 pm" src="https://user-images.githubusercontent.com/2100552/61702452-2683be80-ad83-11e9-8fb5-29f8e9732cfc.png">

**Comment by damolp** [comment]
@hansbogert try using https://github.com/Flood-UI/flood/pull/818/commits/6479a76fe16467ad21d865d8c2b42eb0e8efc358

**Comment by hansbogert** [comment]
Wow, that's nifty. Never got into node before this. Will try once I have the time. Thanks for this so far.

**Comment by noraj** [comment]
maybe related to https://github.com/Flood-UI/flood/issues/224

**Comment by hansbogert** [comment]
can no longer reproduce with newer version. Will create issue if I can reproduce again.
