### ISSUE TITLE
Any plans for official docker image?

### ISSUE THREAD

**Issue by WithoutCaps** [Flood-UI/flood#821]
Type: Feature Request

- [x] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary
I would like to see some sort of official docker image

## Idea of implementation
Addition of webhook which would triger a job that would build and upload Docker image to Docker Hub

**Comment by noraj** [comment]
There is already https://github.com/Flood-UI/flood/blob/master/Dockerfile

**Comment by noraj** [comment]
And if you meant to have an image automatically pushed to docker hub this is a duplicate of https://github.com/Flood-UI/flood/issues/448

**Comment by WithoutCaps** [comment]
@noraj Just so you know: https://nickjanetakis.com/blog/differences-between-a-dockerfile-docker-image-and-docker-container

**Comment by noraj** [comment]
@WithoutCaps yeah I know the diff, you can build the image from the Dockerfile by using `docker build -t flood-github .` as said in the wiki.
