### ISSUE TITLE
HTTP Basic AUthentication on RUTorrent

### ISSUE THREAD

**Issue by Goob00000** [Flood-UI/flood#824]
Type: Feature Request

## Idea of implementation
Add the ability to connect to the RUTorrent API on a remote RUTorrent instance when it is protected by HTTP Basic Authentication. Perhaps there is a way to already do this through configuration but it is not documented. It could just mean allowing a totally custom URL like http://user:pass@host.domain.com:443/path/to/api

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/64136132-d5d69b00-cdef-11e9-9998-708ccac20aed.png)

`Add HTTP Basic authentication support` doesn't really mean something as basic auth is provided by a reverse web proxy so the feature is rather removing auth from flood an let a reverse proxy (let's say nginx) add a basic auth in front of flood (see the already existing issue here #240).
