### ISSUE TITLE
Contextual menu on touch screen

### ISSUE THREAD

**Issue by Aohzan** [Flood-UI/flood#826]
Type: Feature Request

- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary
Hello,
Is it possible to get the contextual menu on touchscreen device (like iPad)? By longpress for example.
Thank you

**Comment by Mati24** [comment]
I just see that it works on Firefox Android, I will check on Safari iPad
My first test was on Firefox iPad

**Comment by Mati24** [comment]
Same problem on Safari

**Comment by erfanio** [comment]
Is this planned to be fixed anytime soon?

**Comment by Aohzan** [comment]
Yes, would be great :)
