### ISSUE TITLE
Creating intermediate directories when adding a torrent

### ISSUE THREAD

**Issue by tommyknows** [Flood-UI/flood#828]
Type: Question

## Automatically create intermediate directories when adding a torrent?

Hi, 
So I feel like I'm missing something super obvious. I'm just getting started with Flood & rtorrent (have been using transmission before), so please bear with me 🙂 

Let's say I have `/` as a base directory (for illustrative purposes).
When adding a torrent and specifying the download dir as `/mynewdownload/`, everything works fine.
When adding a torrent and using, for example, `/test/subdir/subdir`, the torrent does not get started until `/test/subdir` is created. 

Coming from Transmission's WebUI, this feels super weird. I would expect the folders to be created automatically.

I have asked on the rtorrent repo (see https://github.com/rakshasa/rtorrent/issues/907), but his answer is not particularly useful for a total newbie like me. Is this something that Flood should handle? 
(I read that a lot of functionality has been implemented by plugins in ruTorrent).

Thanks!

**Comment by noraj** [comment]
Your right, folders are not created automatically, they must exist before.

**Comment by tommyknows** [comment]
Could this be something that Flood will do?

**Comment by noraj** [comment]
@tommyknows This project has only one spare-time dev, 147 open issues and this one is by far one of the less critical. Also I think this is a sane behavior that Flood don't manage the file system automatically. It could be a plugin or something but Flood doesn't have a plugin engine yet. So sorry but I'll close this except if you want to develop the feature directly.
