### ISSUE TITLE
Download a torrent where one file has a & in the filename

### ISSUE THREAD

**Issue by sktt** [Flood-UI/flood#843]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Node.js version `node --version`: 12.6
* Operating System and version: Linux debian stretch, rtorrent 0.9.6

## Summary
Filenames with & seems to crash when downloading through the UI.

## Possible Solution
See https://github.com/Flood-UI/flood/pull/842

## Steps to Reproduce
1. `touch test&.txt`
2. mktorrent -a "udp://x.x:80" test&.txt
3. Add it to flood,
4. Try to download the file.

**Comment by jesec** [comment]
Resolved by #842.

Feel free to close the issue if it is no longer relevant.

**Comment by sktt** [comment]
Sweet!
