### ISSUE TITLE
rtorrent and flood

### ISSUE THREAD

**Issue by robertparkerx** [Flood-UI/flood#862]
Type: Question
I am having trouble getting flood to run. I have another service that is running on 3000 so I changed the port to 4000. I cp config.template.js config.js and set the port. I try to run it and the process starts, I can see it in ps aux but then it will stop. I'm not sure how to debug.

**Comment by robertparkerx** [comment]
I fixed my issue by changing 127.0.0.1 to my server ip

**Comment by xiego** [comment]
Please close this issue
