### ISSUE TITLE
Remove build depency for static assets

### ISSUE THREAD

**Issue by mrobitaille** [Flood-UI/flood#867]
Type: Feature Request

- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary

Changing the baseURI requires the project to be rebuilt so it is applied to the static assets; this is not very package friendly (ie. pacman / archlinux). 

## Idea of implementation

Something similar to Sonarr/Jackett which both redirect to `localhost:<port>/<baseURI>` when requesting `localhost:<port>` and allow to set the baseURI through the WebUI.

**Comment by jesec** [comment]
Build dependency on config is removed in newer versions of Flood.

Feel free to close the issue if it is no longer relevant.
